/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 house.glb 
Author: Joan Tieu (https://sketchfab.com/JoanTieu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dae-final-assignment-milestone-house-58a9edfc71ab4adc869061d4e5e862d1
Title: [DAE] Final Assignment Milestone: House
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function House(props) {
  const { nodes, materials } = useGLTF('models/house.glb');
  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, Math.PI / 2, 0]}
      position={[-3, 0, 1]}
    >
      <group scale={0.004}>
        <mesh
          geometry={nodes.MainHouse_01_geo_Decals_02_tex_0.geometry}
          material={materials.Decals_02_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_WoodPlanks_01_tex_0.geometry}
          material={materials.WoodPlanks_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_Pipes_01_tex_0.geometry}
          material={materials.Pipes_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_RidgeEnds_01_tex_0.geometry}
          material={materials.RidgeEnds_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_Ridges_01_tex_0.geometry}
          material={materials.Ridges_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_WoodenWall_01_tex_0.geometry}
          material={materials.WoodenWall_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_Walls_01_tex_0.geometry}
          material={materials.Walls_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_Rooftop_01_tex_0.geometry}
          material={materials.Rooftop_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_StoneWall_01_tex_0.geometry}
          material={materials.StoneWall_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_WindowFrame_01_tex_0.geometry}
          material={materials.WindowFrame_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_FrontDoor_01_tex_0.geometry}
          material={materials.FrontDoor_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_Windows_01_tex_0.geometry}
          material={materials.Windows_01_tex}
        />
        <mesh
          geometry={nodes.MainHouse_01_geo_Decals_01_tex_0.geometry}
          material={materials.Decals_01_tex}
        />
      </group>
    </group>
  );
}

useGLTF.preload('models/house.glb');
