/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 japanese_shrine_lantern.glb 
Author: Sam Feng (https://sketchfab.com/fengyuan20000303)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/japanese-shrine-lantern-8c19d6525acf441b9cf3c1fd91598ff6
Title: Japanese Shrine Lantern
*/

import { useGLTF } from '@react-three/drei';

export function Lantern(props) {
  const { nodes, materials } = useGLTF('models/japanese_shrine_lantern.glb');
  return (
    <group {...props} dispose={null} position={[0, -0.5, 2]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 589.825, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={80}
          >
            <mesh
              geometry={nodes.Cube001_Lantern_0.geometry}
              material={materials.Lantern}
            />
            <mesh
              geometry={nodes.Cube001_Light_0.geometry}
              material={materials.Light}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('models/japanese_shrine_lantern.glb');
